"""sync_all_phase3_columns

Revision ID: 0e6578416d46
Revises: b8c4d2e3f5a6
Create Date: 2026-03-12 21:55:22.621757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6578416d46'
down_revision: Union[str, Sequence[str], None] = 'b8c4d2e3f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('risk_appetite_score', sa.Float(), nullable=True),
    sa.Column('risk_appetite_label', sa.String(length=30), nullable=True),
    sa.Column('market_focus_data', sa.JSON(), nullable=True),
    sa.Column('market_focus_entropy', sa.Float(), nullable=True),
    sa.Column('timing_heatmap', sa.JSON(), nullable=True),
    sa.Column('decision_style_score', sa.Float(), nullable=True),
    sa.Column('decision_style_label', sa.String(length=30), nullable=True),
    sa.Column('collaboration_score', sa.Float(), nullable=True),
    sa.Column('collaboration_label', sa.String(length=30), nullable=True),
    sa.Column('learning_velocity_score', sa.Float(), nullable=True),
    sa.Column('learning_velocity_label', sa.String(length=30), nullable=True),
    sa.Column('resilience_score', sa.Float(), nullable=True),
    sa.Column('resilience_label', sa.String(length=30), nullable=True),
    sa.Column('raw_scores', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('dominant_regime', sa.String(length=20), nullable=True),
    sa.Column('regime_distribution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_behavioral_profiles_agent', 'behavioral_profiles', ['agent_id'], unique=False)
    op.create_index('ix_behavioral_profiles_eval', 'behavioral_profiles', ['evaluation_id'], unique=False)
    op.create_table('dynasties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('founder_id', sa.Integer(), nullable=False),
    sa.Column('founder_name', sa.String(length=100), nullable=False),
    sa.Column('founder_role', sa.String(length=50), nullable=False),
    sa.Column('dynasty_name', sa.String(length=200), nullable=False),
    sa.Column('founded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extinct_at', sa.DateTime(), nullable=True),
    sa.Column('total_generations', sa.Integer(), nullable=False),
    sa.Column('total_members', sa.Integer(), nullable=False),
    sa.Column('living_members', sa.Integer(), nullable=False),
    sa.Column('peak_members', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('avg_lifespan_days', sa.Float(), nullable=True),
    sa.Column('longest_living_id', sa.Integer(), nullable=True),
    sa.Column('best_performer_id', sa.Integer(), nullable=True),
    sa.Column('best_performer_pnl', sa.Float(), nullable=False),
    sa.Column('avg_generational_improvement', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['best_performer_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['founder_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['longest_living_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('cycle_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('context_mode', sa.String(length=20), nullable=False),
    sa.Column('context_tokens', sa.Integer(), nullable=False),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('recent_pattern', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('action_params', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('self_note', sa.Text(), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('validation_retries', sa.Integer(), nullable=False),
    sa.Column('warden_flags', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('outcome_pnl', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('api_cost_usd', sa.Float(), nullable=False),
    sa.Column('cycle_duration_ms', sa.Integer(), nullable=False),
    sa.Column('api_latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_cycles_agent_id_cycle', 'agent_cycles', ['agent_id', 'cycle_number'], unique=False)
    op.create_index('ix_agent_cycles_agent_id_timestamp', 'agent_cycles', ['agent_id', 'timestamp'], unique=False)
    op.create_table('agent_equity_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equity_snapshots_agent_time', 'agent_equity_snapshots', ['agent_id', 'snapshot_at'], unique=False)
    op.create_table('agent_long_term_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_cycle', sa.Integer(), nullable=True),
    sa.Column('times_confirmed', sa.Integer(), nullable=False),
    sa.Column('times_contradicted', sa.Integer(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('demoted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_ltm_agent_active', 'agent_long_term_memory', ['agent_id', 'is_active'], unique=False)
    op.create_table('agent_reflections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('what_worked', sa.Text(), nullable=True),
    sa.Column('what_failed', sa.Text(), nullable=True),
    sa.Column('pattern_detected', sa.Text(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=True),
    sa.Column('confidence_trend', sa.String(length=20), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('strategy_note', sa.Text(), nullable=True),
    sa.Column('memory_promotions', sa.JSON(), nullable=True),
    sa.Column('memory_demotions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_reflections_agent_id', 'agent_reflections', ['agent_id'], unique=False)
    op.create_table('agent_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('target_agent_id', sa.Integer(), nullable=False),
    sa.Column('target_agent_name', sa.String(length=100), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('positive_outcomes', sa.Integer(), nullable=False),
    sa.Column('negative_outcomes', sa.Integer(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('last_assessment', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archive_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'target_agent_id', name='uq_agent_relationship')
    )
    op.create_index('ix_agent_relationships_agent', 'agent_relationships', ['agent_id'], unique=False)
    op.create_index('ix_agent_relationships_target', 'agent_relationships', ['target_agent_id'], unique=False)
    op.create_table('boot_sequence_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wave_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_boot_log_wave_event', 'boot_sequence_log', ['wave_number', 'event_type'], unique=False)
    op.create_table('divergence_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_a_id', sa.Integer(), nullable=False),
    sa.Column('agent_b_id', sa.Integer(), nullable=False),
    sa.Column('agent_a_role', sa.String(length=50), nullable=False),
    sa.Column('divergence_score', sa.Float(), nullable=False),
    sa.Column('comparable_metrics', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_a_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['agent_b_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_divergence_scores_agents', 'divergence_scores', ['agent_a_id', 'agent_b_id'], unique=False)
    op.create_index('ix_divergence_scores_eval', 'divergence_scores', ['evaluation_id'], unique=False)
    op.create_table('memorials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_role', sa.String(length=50), nullable=False),
    sa.Column('dynasty_name', sa.String(length=200), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('lifespan_days', sa.Float(), nullable=False),
    sa.Column('cause_of_death', sa.String(length=200), nullable=False),
    sa.Column('total_cycles', sa.Integer(), nullable=False),
    sa.Column('final_prestige', sa.String(length=50), nullable=True),
    sa.Column('best_metric_name', sa.String(length=100), nullable=True),
    sa.Column('best_metric_value', sa.Float(), nullable=True),
    sa.Column('worst_metric_name', sa.String(length=100), nullable=True),
    sa.Column('worst_metric_value', sa.Float(), nullable=True),
    sa.Column('notable_achievement', sa.Text(), nullable=True),
    sa.Column('final_pnl', sa.Float(), nullable=False),
    sa.Column('epitaph', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memorials_agent', 'memorials', ['agent_id'], unique=False)
    op.create_table('study_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('studied_at_cycle', sa.Integer(), nullable=False),
    sa.Column('studied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_study_history_agent', 'study_history', ['agent_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scout_agent_id', sa.Integer(), nullable=False),
    sa.Column('scout_agent_name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=30), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('claimed_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('converted_to_plan_id', sa.Integer(), nullable=True),
    sa.Column('agora_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agora_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['claimed_by_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['scout_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_scout', 'opportunities', ['scout_agent_id'], unique=False)
    op.create_index('ix_opportunities_status_created', 'opportunities', ['status', 'created_at'], unique=False)
    op.create_table('post_mortems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_role', sa.String(length=50), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('what_went_wrong', sa.Text(), nullable=False),
    sa.Column('what_went_right', sa.Text(), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('market_context', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('genesis_visible', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('library_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['library_entry_id'], ['library_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_mortems_publish_at', 'post_mortems', ['publish_at'], unique=False)
    op.create_index('ix_post_mortems_published', 'post_mortems', ['published'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategist_agent_id', sa.Integer(), nullable=False),
    sa.Column('strategist_agent_name', sa.String(length=100), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('market', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_conditions', sa.Text(), nullable=False),
    sa.Column('exit_conditions', sa.Text(), nullable=False),
    sa.Column('position_size_pct', sa.Float(), nullable=False),
    sa.Column('timeframe', sa.String(length=50), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('critic_agent_id', sa.Integer(), nullable=True),
    sa.Column('critic_agent_name', sa.String(length=100), nullable=True),
    sa.Column('critic_verdict', sa.String(length=20), nullable=True),
    sa.Column('critic_reasoning', sa.Text(), nullable=True),
    sa.Column('critic_risk_notes', sa.Text(), nullable=True),
    sa.Column('operator_agent_id', sa.Integer(), nullable=True),
    sa.Column('operator_agent_name', sa.String(length=100), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['critic_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['operator_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['strategist_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plans_status', 'plans', ['status'], unique=False)
    op.create_index('ix_plans_strategist', 'plans', ['strategist_agent_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('size_usd', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl_pct', sa.Float(), nullable=False),
    sa.Column('fees_entry', sa.Float(), nullable=False),
    sa.Column('fees_exit', sa.Float(), nullable=True),
    sa.Column('source_plan_id', sa.Integer(), nullable=True),
    sa.Column('source_opp_id', sa.Integer(), nullable=True),
    sa.Column('source_cycle_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('close_reason', sa.String(length=30), nullable=True),
    sa.Column('execution_venue', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['source_cycle_id'], ['agent_cycles.id'], ),
    sa.ForeignKeyConstraint(['source_opp_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['source_plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_agent_status', 'positions', ['agent_id', 'status'], unique=False)
    op.create_index('ix_positions_symbol_status', 'positions', ['symbol', 'status'], unique=False)
    op.create_table('rejection_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('critic_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('timeframe', sa.String(length=50), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=False),
    sa.Column('check_until', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('outcome_price', sa.Float(), nullable=True),
    sa.Column('outcome_pnl_pct', sa.Float(), nullable=True),
    sa.Column('critic_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['critic_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rejection_tracking_critic', 'rejection_tracking', ['critic_id'], unique=False)
    op.create_index('ix_rejection_tracking_status', 'rejection_tracking', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('requested_size_usd', sa.Float(), nullable=False),
    sa.Column('requested_price', sa.Float(), nullable=True),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('fill_quantity', sa.Float(), nullable=True),
    sa.Column('fill_value_usd', sa.Float(), nullable=True),
    sa.Column('slippage_pct', sa.Float(), nullable=True),
    sa.Column('fee_usd', sa.Float(), nullable=True),
    sa.Column('fee_rate', sa.Float(), nullable=True),
    sa.Column('market_bid', sa.Float(), nullable=True),
    sa.Column('market_ask', sa.Float(), nullable=True),
    sa.Column('market_spread_pct', sa.Float(), nullable=True),
    sa.Column('market_volume_24h', sa.Float(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('reserved_amount', sa.Float(), nullable=True),
    sa.Column('reservation_released', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('source_plan_id', sa.Integer(), nullable=True),
    sa.Column('source_cycle_id', sa.Integer(), nullable=True),
    sa.Column('warden_request_id', sa.String(length=50), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('execution_venue', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['source_cycle_id'], ['agent_cycles.id'], ),
    sa.ForeignKeyConstraint(['source_plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_agent_status', 'orders', ['agent_id', 'status'], unique=False)
    op.create_index('ix_orders_symbol_status', 'orders', ['symbol', 'status'], unique=False)
    op.add_column('agents', sa.Column('cycle_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('last_cycle_at', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('avg_cycle_cost', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('avg_cycle_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('idle_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('validation_fail_rate', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('warden_violation_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('current_context_mode', sa.String(length=20), nullable=False, server_default='normal'))
    op.add_column('agents', sa.Column('api_temperature', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('watched_markets', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('spawn_wave', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('orientation_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('agents', sa.Column('orientation_failed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('agents', sa.Column('health_check_passed', sa.Boolean(), nullable=True))
    op.add_column('agents', sa.Column('health_check_at', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('initial_watchlist', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('cash_balance', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('reserved_cash', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('total_equity', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('realized_pnl', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('unrealized_pnl', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('total_fees_paid', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('position_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('pending_evaluation', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('agents', sa.Column('probation', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('agents', sa.Column('probation_grace_cycles', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('ecosystem_contribution', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('role_rank', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('last_evaluation_id', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('evaluation_scorecard', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('last_temperature_signal', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('temperature_history', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('identity_tier', sa.String(length=20), nullable=False, server_default='new'))
    op.add_column('agents', sa.Column('behavioral_profile_id', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('dynasty_id', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('offspring_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agents', sa.Column('last_reproduction_at', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('reproduction_cooldown_until', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('founding_directive', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('founding_directive_consumed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('agents', sa.Column('posthumous_birth', sa.Boolean(), nullable=False, server_default='false'))
    op.create_foreign_key(None, 'agents', 'evaluations', ['last_evaluation_id'], ['id'])
    op.create_foreign_key(None, 'agents', 'dynasties', ['dynasty_id'], ['id'])
    op.create_foreign_key(None, 'agents', 'behavioral_profiles', ['behavioral_profile_id'], ['id'])
    op.add_column('evaluations', sa.Column('agent_name', sa.String(length=100), nullable=True))
    op.add_column('evaluations', sa.Column('agent_role', sa.String(length=50), nullable=True))
    op.add_column('evaluations', sa.Column('generation', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('evaluation_number', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('evaluation_period_start', sa.DateTime(), nullable=True))
    op.add_column('evaluations', sa.Column('evaluation_period_end', sa.DateTime(), nullable=True))
    op.add_column('evaluations', sa.Column('evaluated_at', sa.DateTime(), nullable=True))
    op.add_column('evaluations', sa.Column('composite_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('metric_breakdown', sa.JSON(), nullable=True))
    op.add_column('evaluations', sa.Column('role_rank', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('role_rank_total', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('ecosystem_contribution_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('ecosystem_rank', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('pre_filter_result', sa.String(length=20), nullable=True))
    op.add_column('evaluations', sa.Column('genesis_decision', sa.String(length=30), nullable=True))
    op.add_column('evaluations', sa.Column('genesis_reasoning', sa.Text(), nullable=True))
    op.add_column('evaluations', sa.Column('survival_clock_new_days', sa.Integer(), nullable=True))
    op.add_column('evaluations', sa.Column('capital_adjustment', sa.String(length=50), nullable=True))
    op.add_column('evaluations', sa.Column('thinking_budget_adjustment', sa.String(length=50), nullable=True))
    op.add_column('evaluations', sa.Column('warning_to_agent', sa.Text(), nullable=True))
    op.add_column('evaluations', sa.Column('market_regime', sa.String(length=20), nullable=True))
    op.add_column('evaluations', sa.Column('alert_hours_during_period', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('regime_adjustment_applied', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('evaluations', sa.Column('first_evaluation', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('evaluations', sa.Column('prestige_before', sa.String(length=50), nullable=True))
    op.add_column('evaluations', sa.Column('prestige_after', sa.String(length=50), nullable=True))
    op.add_column('evaluations', sa.Column('capital_before', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('capital_after', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('thinking_budget_before', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('thinking_budget_after', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('api_cost_for_evaluation', sa.Float(), nullable=True))
    op.create_index('ix_evaluations_agent_evaluated', 'evaluations', ['agent_id', 'evaluated_at'], unique=False)
    op.add_column('lineage', sa.Column('agent_name', sa.String(length=100), nullable=True))
    op.add_column('lineage', sa.Column('dynasty_id', sa.Integer(), nullable=True))
    op.add_column('lineage', sa.Column('grandparent_id', sa.Integer(), nullable=True))
    op.add_column('lineage', sa.Column('inherited_memories_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('lineage', sa.Column('inherited_temperature', sa.Float(), nullable=True))
    op.add_column('lineage', sa.Column('mutations_applied', sa.JSON(), nullable=True))
    op.add_column('lineage', sa.Column('founding_directive', sa.Text(), nullable=True))
    op.add_column('lineage', sa.Column('posthumous_birth', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('lineage', sa.Column('parent_profile_snapshot', sa.JSON(), nullable=True))
    op.add_column('lineage', sa.Column('parent_composite_at_reproduction', sa.Float(), nullable=True))
    op.add_column('lineage', sa.Column('parent_prestige_at_reproduction', sa.String(length=50), nullable=True))
    op.add_column('lineage', sa.Column('died_at', sa.DateTime(), nullable=True))
    op.add_column('lineage', sa.Column('cause_of_death', sa.String(length=200), nullable=True))
    op.add_column('lineage', sa.Column('lifespan_days', sa.Float(), nullable=True))
    op.add_column('lineage', sa.Column('final_composite', sa.Float(), nullable=True))
    op.add_column('lineage', sa.Column('final_pnl', sa.Float(), nullable=True))
    op.add_column('lineage', sa.Column('final_prestige', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'lineage', 'dynasties', ['dynasty_id'], ['id'])
    op.create_foreign_key(None, 'lineage', 'agents', ['grandparent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lineage', type_='foreignkey')
    op.drop_constraint(None, 'lineage', type_='foreignkey')
    op.drop_column('lineage', 'final_prestige')
    op.drop_column('lineage', 'final_pnl')
    op.drop_column('lineage', 'final_composite')
    op.drop_column('lineage', 'lifespan_days')
    op.drop_column('lineage', 'cause_of_death')
    op.drop_column('lineage', 'died_at')
    op.drop_column('lineage', 'parent_prestige_at_reproduction')
    op.drop_column('lineage', 'parent_composite_at_reproduction')
    op.drop_column('lineage', 'parent_profile_snapshot')
    op.drop_column('lineage', 'posthumous_birth')
    op.drop_column('lineage', 'founding_directive')
    op.drop_column('lineage', 'mutations_applied')
    op.drop_column('lineage', 'inherited_temperature')
    op.drop_column('lineage', 'inherited_memories_count')
    op.drop_column('lineage', 'grandparent_id')
    op.drop_column('lineage', 'dynasty_id')
    op.drop_column('lineage', 'agent_name')
    op.drop_index('ix_evaluations_agent_evaluated', table_name='evaluations')
    op.drop_column('evaluations', 'api_cost_for_evaluation')
    op.drop_column('evaluations', 'thinking_budget_after')
    op.drop_column('evaluations', 'thinking_budget_before')
    op.drop_column('evaluations', 'capital_after')
    op.drop_column('evaluations', 'capital_before')
    op.drop_column('evaluations', 'prestige_after')
    op.drop_column('evaluations', 'prestige_before')
    op.drop_column('evaluations', 'first_evaluation')
    op.drop_column('evaluations', 'regime_adjustment_applied')
    op.drop_column('evaluations', 'alert_hours_during_period')
    op.drop_column('evaluations', 'market_regime')
    op.drop_column('evaluations', 'warning_to_agent')
    op.drop_column('evaluations', 'thinking_budget_adjustment')
    op.drop_column('evaluations', 'capital_adjustment')
    op.drop_column('evaluations', 'survival_clock_new_days')
    op.drop_column('evaluations', 'genesis_reasoning')
    op.drop_column('evaluations', 'genesis_decision')
    op.drop_column('evaluations', 'pre_filter_result')
    op.drop_column('evaluations', 'ecosystem_rank')
    op.drop_column('evaluations', 'ecosystem_contribution_score')
    op.drop_column('evaluations', 'role_rank_total')
    op.drop_column('evaluations', 'role_rank')
    op.drop_column('evaluations', 'metric_breakdown')
    op.drop_column('evaluations', 'composite_score')
    op.drop_column('evaluations', 'evaluated_at')
    op.drop_column('evaluations', 'evaluation_period_end')
    op.drop_column('evaluations', 'evaluation_period_start')
    op.drop_column('evaluations', 'evaluation_number')
    op.drop_column('evaluations', 'generation')
    op.drop_column('evaluations', 'agent_role')
    op.drop_column('evaluations', 'agent_name')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'posthumous_birth')
    op.drop_column('agents', 'founding_directive_consumed')
    op.drop_column('agents', 'founding_directive')
    op.drop_column('agents', 'reproduction_cooldown_until')
    op.drop_column('agents', 'last_reproduction_at')
    op.drop_column('agents', 'offspring_count')
    op.drop_column('agents', 'dynasty_id')
    op.drop_column('agents', 'behavioral_profile_id')
    op.drop_column('agents', 'identity_tier')
    op.drop_column('agents', 'temperature_history')
    op.drop_column('agents', 'last_temperature_signal')
    op.drop_column('agents', 'evaluation_scorecard')
    op.drop_column('agents', 'last_evaluation_id')
    op.drop_column('agents', 'role_rank')
    op.drop_column('agents', 'ecosystem_contribution')
    op.drop_column('agents', 'probation_grace_cycles')
    op.drop_column('agents', 'probation')
    op.drop_column('agents', 'pending_evaluation')
    op.drop_column('agents', 'position_count')
    op.drop_column('agents', 'total_fees_paid')
    op.drop_column('agents', 'unrealized_pnl')
    op.drop_column('agents', 'realized_pnl')
    op.drop_column('agents', 'total_equity')
    op.drop_column('agents', 'reserved_cash')
    op.drop_column('agents', 'cash_balance')
    op.drop_column('agents', 'initial_watchlist')
    op.drop_column('agents', 'health_check_at')
    op.drop_column('agents', 'health_check_passed')
    op.drop_column('agents', 'orientation_failed')
    op.drop_column('agents', 'orientation_completed')
    op.drop_column('agents', 'spawn_wave')
    op.drop_column('agents', 'watched_markets')
    op.drop_column('agents', 'api_temperature')
    op.drop_column('agents', 'current_context_mode')
    op.drop_column('agents', 'warden_violation_count')
    op.drop_column('agents', 'validation_fail_rate')
    op.drop_column('agents', 'idle_rate')
    op.drop_column('agents', 'avg_cycle_tokens')
    op.drop_column('agents', 'avg_cycle_cost')
    op.drop_column('agents', 'last_cycle_at')
    op.drop_column('agents', 'cycle_count')
    op.drop_index('ix_orders_symbol_status', table_name='orders')
    op.drop_index('ix_orders_agent_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_rejection_tracking_status', table_name='rejection_tracking')
    op.drop_index('ix_rejection_tracking_critic', table_name='rejection_tracking')
    op.drop_table('rejection_tracking')
    op.drop_index('ix_positions_symbol_status', table_name='positions')
    op.drop_index('ix_positions_agent_status', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_plans_strategist', table_name='plans')
    op.drop_index('ix_plans_status', table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_post_mortems_published', table_name='post_mortems')
    op.drop_index('ix_post_mortems_publish_at', table_name='post_mortems')
    op.drop_table('post_mortems')
    op.drop_index('ix_opportunities_status_created', table_name='opportunities')
    op.drop_index('ix_opportunities_scout', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_study_history_agent', table_name='study_history')
    op.drop_table('study_history')
    op.drop_index('ix_memorials_agent', table_name='memorials')
    op.drop_table('memorials')
    op.drop_index('ix_divergence_scores_eval', table_name='divergence_scores')
    op.drop_index('ix_divergence_scores_agents', table_name='divergence_scores')
    op.drop_table('divergence_scores')
    op.drop_index('ix_boot_log_wave_event', table_name='boot_sequence_log')
    op.drop_table('boot_sequence_log')
    op.drop_index('ix_agent_relationships_target', table_name='agent_relationships')
    op.drop_index('ix_agent_relationships_agent', table_name='agent_relationships')
    op.drop_table('agent_relationships')
    op.drop_index('ix_agent_reflections_agent_id', table_name='agent_reflections')
    op.drop_table('agent_reflections')
    op.drop_index('ix_agent_ltm_agent_active', table_name='agent_long_term_memory')
    op.drop_table('agent_long_term_memory')
    op.drop_index('ix_equity_snapshots_agent_time', table_name='agent_equity_snapshots')
    op.drop_table('agent_equity_snapshots')
    op.drop_index('ix_agent_cycles_agent_id_timestamp', table_name='agent_cycles')
    op.drop_index('ix_agent_cycles_agent_id_cycle', table_name='agent_cycles')
    op.drop_table('agent_cycles')
    op.drop_table('dynasties')
    op.drop_index('ix_behavioral_profiles_eval', table_name='behavioral_profiles')
    op.drop_index('ix_behavioral_profiles_agent', table_name='behavioral_profiles')
    op.drop_table('behavioral_profiles')
    # ### end Alembic commands ###
