"""initial schema - agents, transactions, messages, evaluations, reputation, sips, system_state, lineage

Revision ID: d033ef2e1ef3
Revises: 
Create Date: 2026-03-12 00:45:40.250060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd033ef2e1ef3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('capital_allocated', sa.Float(), nullable=False),
    sa.Column('capital_current', sa.Float(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('prestige_title', sa.String(length=50), nullable=True),
    sa.Column('survival_clock_start', sa.DateTime(), nullable=True),
    sa.Column('survival_clock_end', sa.DateTime(), nullable=True),
    sa.Column('survival_clock_paused', sa.Boolean(), nullable=False),
    sa.Column('thinking_budget_daily', sa.Float(), nullable=False),
    sa.Column('thinking_budget_used_today', sa.Float(), nullable=False),
    sa.Column('api_cost_total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('termination_reason', sa.String(length=500), nullable=True),
    sa.Column('strategy_summary', sa.Text(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_treasury', sa.Float(), nullable=False),
    sa.Column('peak_treasury', sa.Float(), nullable=False),
    sa.Column('current_regime', sa.String(length=20), nullable=False),
    sa.Column('active_agent_count', sa.Integer(), nullable=False),
    sa.Column('last_backup_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_type', sa.String(length=30), nullable=False),
    sa.Column('pnl_gross', sa.Float(), nullable=False),
    sa.Column('pnl_net', sa.Float(), nullable=False),
    sa.Column('api_cost', sa.Float(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('reputation_change', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineage',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('lineage_path', sa.String(length=500), nullable=True),
    sa.Column('strategy_heritage_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposing_agent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('votes_for', sa.Integer(), nullable=False),
    sa.Column('votes_against', sa.Integer(), nullable=False),
    sa.Column('owner_decision', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposing_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reputation_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_agent_id', sa.Integer(), nullable=True),
    sa.Column('to_agent_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('related_trade_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['related_trade_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reputation_transactions')
    op.drop_table('transactions')
    op.drop_table('sips')
    op.drop_table('messages')
    op.drop_table('lineage')
    op.drop_table('evaluations')
    op.drop_table('system_state')
    op.drop_table('agents')
    # ### end Alembic commands ###
