"""Phase 1: add agent Phase 1 columns, inherited_positions, market_regimes, daily_reports

Revision ID: d24866bf2818
Revises: d033ef2e1ef3
Create Date: 2026-03-12 01:11:34.186074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24866bf2818'
down_revision: Union[str, Sequence[str], None] = 'd033ef2e1ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_regimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('btc_price', sa.Float(), nullable=False),
    sa.Column('btc_ma_20', sa.Float(), nullable=False),
    sa.Column('btc_ma_50', sa.Float(), nullable=False),
    sa.Column('btc_volatility_30d', sa.Float(), nullable=False),
    sa.Column('btc_dominance', sa.Float(), nullable=False),
    sa.Column('total_market_cap', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('treasury_balance', sa.Float(), nullable=False),
    sa.Column('treasury_change_24h', sa.Float(), nullable=False),
    sa.Column('active_agents', sa.Integer(), nullable=False),
    sa.Column('agents_born', sa.Integer(), nullable=False),
    sa.Column('agents_died', sa.Integer(), nullable=False),
    sa.Column('agents_hibernating', sa.Integer(), nullable=False),
    sa.Column('top_performer_id', sa.Integer(), nullable=True),
    sa.Column('worst_performer_id', sa.Integer(), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=False),
    sa.Column('alert_status', sa.String(length=20), nullable=False),
    sa.Column('total_api_cost_24h', sa.Float(), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['top_performer_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['worst_performer_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_table('inherited_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_agent_id', sa.Integer(), nullable=False),
    sa.Column('inherited_by', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('inherited_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['original_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('composite_score', sa.Float(), nullable=False))
    op.add_column('agents', sa.Column('hibernation_start', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('hibernation_reason', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('total_api_cost', sa.Float(), nullable=False))
    op.add_column('agents', sa.Column('total_gross_pnl', sa.Float(), nullable=False))
    op.add_column('agents', sa.Column('total_true_pnl', sa.Float(), nullable=False))
    op.add_column('agents', sa.Column('evaluation_count', sa.Integer(), nullable=False))
    op.add_column('agents', sa.Column('profitable_evaluations', sa.Integer(), nullable=False))
    op.add_column('system_state', sa.Column('alert_status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_state', 'alert_status')
    op.drop_column('agents', 'profitable_evaluations')
    op.drop_column('agents', 'evaluation_count')
    op.drop_column('agents', 'total_true_pnl')
    op.drop_column('agents', 'total_gross_pnl')
    op.drop_column('agents', 'total_api_cost')
    op.drop_column('agents', 'hibernation_reason')
    op.drop_column('agents', 'hibernation_start')
    op.drop_column('agents', 'composite_score')
    op.drop_table('inherited_positions')
    op.drop_table('daily_reports')
    op.drop_table('market_regimes')
    # ### end Alembic commands ###
